import { Sheet } from './types';
import { getHingeHoles } from './drawing'; // Reuse the pure logic!

export function generateGCode(sheet: Sheet): string {
    let g = '';

    // Header
    g += '(Generated by ShopFlow)\n';
    g += 'G17 G20 G40 G80 G90\n'; // XY Plane, Inches, Cancel Comp/Cycles, Absolute
    g += 'G0 Z0.5\n'; // Safe Z
    g += 'M3 S18000\n'; // Spindle On

    // Tools
    const DRILL_T1 = 1;
    const CUTOUT_T2 = 2;

    // 1. Drilling Operations
    g += '\n(DRILLING)\n';
    g += `T${DRILL_T1} M6\n`;

    sheet.parts.forEach(p => {
        // We need hinge settings again. 
        // Ideally these come from the Part or passed global settings.
        // Assuming defaults (left, 2 hinges) or part properties if saved.
        // We use the same getHingeHoles logic.
        const holes = p.type === 'door' ? getHingeHoles(p, p.hingeSide || 'left', 2, { bottomInset: 3, topInset: 3 }) : [];

        holes.forEach(h => {
            // Coordinate transform: Part -> Sheet
            // Part (0,0) is bottom-left relative to itself.
            // Sheet (0,0) is usually bottom-left.
            // Part placed at p.x, p.y.
            // Hole x,y is relative to part origin.
            const absX = p.x + h.x;
            const absY = p.y + h.y;

            g += `G0 X${absX.toFixed(4)} Y${absY.toFixed(4)}\n`;
            g += 'G1 Z-0.5 F50\n'; // Drill depth
            g += 'G0 Z0.2\n'; // Retract
        });
    });

    // 2. Cutout Operations
    g += '\n(PROFILE CUTOUT)\n';
    g += `T${CUTOUT_T2} M6\n`;

    sheet.parts.forEach(p => {
        // Rectangle profile
        const x1 = p.x;
        const y1 = p.y;
        const x2 = p.x + p.width;
        const y2 = p.y + p.height;

        g += `G0 X${x1.toFixed(4)} Y${y1.toFixed(4)}\n`;
        g += 'G1 Z-0.75 F100\n'; // Cut depth
        g += `G1 Y${y2.toFixed(4)}\n`;
        g += `G1 X${x2.toFixed(4)}\n`;
        g += `G1 Y${y1.toFixed(4)}\n`;
        g += `G1 X${x1.toFixed(4)}\n`; // Close loop
        g += 'G0 Z0.5\n';
    });

    g += 'M5\n'; // Spindle Off
    g += 'M30\n'; // End Program

    return g;
}
